### PR TITLE
Update generated documentation for contributing page

### PR DESCRIPTION
**Pull request by Regent**

### CODE REVIEW

**Comment by simra** [comment]
Checking: this PR is into gh-pages, rather than master.  It seems to be a distinct PR from #98 but I get the impression it's not necessary because the gh-pages branch is auto-generated.  I'll wait for @tpetricek or @dsyme to weigh in.

**Comment by Regent** [comment]
I can see that @dsyme updated gh-pages recently but apparently he did it before you approved #98 since those are not on the site yet.

**Comment by simra** [comment]
Thanks- I had the impression from @tpetricek that the gh-pages branch is auto-generated and no action is necessary.  I'm not sure what triggers the merge, so I'll dig deeper this evening.

**Comment by Regent** [comment]
I think although it is auto-generated it is not auto-commiting. :)

**Comment by tpetricek** [comment]
The `gh-pages` is updated when we release a new version of the library (which is done by running `build Release` locally). So we do not need to merge this PR, just run the release script again (which I'll do).

**Pull request closed without merging**
