### PR TITLE
[WiP] PR to introduce a histogram chart type

### PR DESCRIPTION
**Pull request by bohdanszymanik**
And hopefully no issues

### CODE REVIEW

**Comment by simra** [comment]
Checking in on this PR.  Is the build failure a blocking issue? I don't have Gtk on my desktop (working on it), so I can't verify that it's an appveyor issue.  Merging the PR on my personal branch to try it out now.

**Comment by bohdanszymanik** [comment]
Whoops - I'm quite new to git/appveyor etc. I didn't get a build failure on my local gtk implementation but the xaxis labels wouldn't appear.

**Comment by simra** [comment]
So am I. :)  Since the build error has nothing to do with the specifics of the PR I suggest we accept the PR and open two issues- one for the build failure and the other for the labeling issue. If I don't get to it tonight I'll tackle this tomorrow.

**Comment by bohdanszymanik** [comment]
I just tried that chocolatey install of gtksharp on a fairly vanilla win2012 server image - worked for me. Not sure why appveyor having issues.

**Comment by simra** [comment]
Ok, merging. Labels display fine in Windows/WPF, so I'll create an issue for GtkSharp.

**Comment by dsyme** [comment]
Nice addition!

**Comment by bohdanszymanik** [comment]
Thanks! First time I've tried to do anything to contribute, it's a lot of fun.

**Pull request merged**
